### ISSUE TITLE
add option to throw errors

### ISSUE THREAD

**Issue by defunctzombie** [mmalecki/json-stream#5]
I want to know when there are parse errors so that I can disconnect the sender. A simple option to the constructor should do :)

**Comment by tomekwi** [comment]
:+1: for this feature!

**Comment by tomekwi** [comment]
> Not sure what my motivation was for disabling this by default.

I’ve had a go at implementing this myself. I found out what your motivation was, and I found it the hard way.

Puzzling fact: all existing tests failed after this simple commit <https://github.com/tomekwi/json-stream/commit/a80ad0f202114e5eb48245c058a4b9f6c7ff3327>. After I’ve noticed that <https://github.com/tomekwi/json-stream/commit/32426837adcf90764d8c9672db4f76c88951f69d> fails while <https://github.com/tomekwi/json-stream/commit/5d682417d7859630b2dfe2c64587f9157b2dda6d> is OK came enlightenment:

You ignore errors so that this is possible: 
```js
parser.write('["first part');
// Error while parsing – gets ignored
parser.write('", "second part"]');
// Now it’s valid – JSON data is emitted
```

**Comment by refractalize** [comment]
Hi all, #9 fixes this by waiting for a `\n` before attempting to parse JSON, and finally by waiting for the `end` event to parse any remaining text (if the file doesn't end with `\n`.) The `end` event is the `_flush()` method on the `Transform` stream.

**Comment by tomek-he-him** [comment]
:+1: Good idea, as far as I can say!

**Comment by jcrugzz** [comment]
The code used to be written in a similar way where it was handled via strings. It was changed to use buffers for much more efficient memory usage. I do not think we want to go backwards on approach here but it does seem reasonable to support errors if you want them to be emitted
